version: '3.9'

services:
  app:
    build: .
    container_name: miniservice_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - ollama

  redis:
    image: redis:7
    container_name: miniservice_redis
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: miniservice_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama: