services:
  miniservice:
    image: miniservice-ai:v2
    container_name: miniservice_app
    ports:
      - "5000:5000"
    volumes:
    
      - .:/app
    networks:
      - ai-net

networks:
  ai-net:
    external: true