version: '3.8'

services:
  miniservice:
    build: .
    container_name: miniservice_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - ollama
    networks:
      - ai-net

networks:
  ai-net:
    external: true